### ISSUE TITLE
Review word2vec usage

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#1]
We currently treat a list of log messages as a single sentence where each log message represents a token

```
[
  [msg1, msg2, msg3, ...]
]
```

Investigate different encoding, where each log message is treated as a sentence. This might be simplified by using doc2vec instead of word2vec directly.

**Comment by zmhassan** [comment]
@vpavlin Seems like this has been merged @MichaelClifford Can you verify if so lets close these issues.
