### ISSUE TITLE
Continuous learning from false positives

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#105]
**Describe the problem**
When users get a false predictions then they should be able to give us feedback. We have a fact-store for this purpose. The next step is to train the model on new log lines and fetch the false predictions that where reported. @MichaelClifford lets discuss what updates need to be done for providing this functionality.

**More Details**
I wanted to start this as a discussion first and then look at what needs to be changed.

**Comment by zmhassan** [comment]
@MichaelClifford could you provide more insight on this?

@durandom ^

**Comment by zmhassan** [comment]
Will this require more data science or does the system currently support feeding false positives and it being able to learn from that?

**Comment by durandom** [comment]
@MichaelClifford IIRC we would just run the "training" code with the false positives, in order to increase the frequency of those log lines, so that they don't look anomalous anymore.

How about true positives? Like "yes, this is an anomaly"? 
AFAIK, we don't capture false negatives. "This should've been an anomaly"

Anyway, let's start with the false positives...

**Comment by MichaelClifford** [comment]
Simply training a model that includes false positive data should not require any additional data science (That said, once this is implemented, more data science may be required to determine how well its performing and decide on other changes). The model currently supports this behaviour. However, the anomaly detection application, AFAIU does not currently support this behaviour. During model training, the fact store should be invoked automatically to collect all false positive messages it has stored and append then to the training dataset. This  should decrease the likelihood that such false positives will be flagged as anomalies. Then during inference, the fact store is used only to obfuscate false anomalies. Let me know if that makes sense.

**Comment by MichaelClifford** [comment]
@durandom yes, lets stick with false positives, I think the other types of errors would require additional/ different SOM models

**Comment by zmhassan** [comment]
@MichaelClifford Can you provide more detail on the format that your expecting as input like Lets say I have a log line:

```bash
2015-10-17 15:42:46,470 INFO [Thread-101] org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler: Stopping JobHistoryEventHandler. Size of the outstanding queue size is 0
```

Do you want this encoded or do you take raw text?

**Comment by MichaelClifford** [comment]
I'm pretty sure that the application requires the data to be in the same format as when it is accessed from ES. I think this is just a list of json objects. And currently we are looking only at the message field of the log, so I believe the following input format should suffice. 

`[{"message": "2015-10-17 15:42:46,470 INFO [Thread-101] org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler: Stopping JobHistoryEventHandler. Size of the outstanding queue size is 0"}]`

**Comment by zmhassan** [comment]
Great. So it will be simple to integrate then.

**Comment by durandom** [comment]
[train](https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/anomaly_detector.py#L94) can be called multiple times, IIUC, and it'll always be trained on the current chunk of data.

So for re-training, we'll want to a version of [_load_data](https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/anomaly_detector.py#L84) that returns just the false positives from storage.

**Comment by zmhassan** [comment]
Good point. I'll work on adding that.
