### ISSUE TITLE
removed locked down packages from Pipfile

### ISSUE THREAD

**Issue by goern** [AICoE/log-anomaly-detector#112]
**Is your feature request related to a problem? Please describe.**
Ja. lockdown is done in Pipfile.lock via pipenv, not in Pipfile itself

**Describe the solution you'd like**
remove all locked down versions from Pipfile if they are not absolutely necessary. 

**Describe alternatives you've considered**
none.

**Additional context**
n/a

**Comment by zmhassan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Process] Investigate automating the process of linting PR's](https://trello.com/c/PtaLLcDM/260-process-investigate-automating-the-process-of-linting-prs)

**Comment by zmhassan** [comment]
@goern PR has been submitted
#113
