### ISSUE TITLE
Break out W2v model into grpc microservice 

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#125]
**Is your feature request related to a problem? Please describe.**
When testing log-anomaly-detector there are multiple steps involved. And repeated steps in the train to inference cycle. w2v model gets recreated every-time. This is redundant.

**Describe the solution you'd like**
Break out word 2 vec model into its own microservice that can be accessed via GRPC.

**Describe alternatives you've considered**
Leave as is

**Additional context**
GRPC - Is a communication protocol that is helpful in creating fast communication between microservices. See https://zakhassan.ca/2019/02/24/grpc-vs-rest/ for more details on what GRPC is.

**Comment by goern** [comment]
please have a look at thoth's stub-api project, it gives a pattern for instrumented rest and grpc services

**Comment by zmhassan** [comment]
@goern Do we have any services currently in production using that? Also do you'll have documentation?

**Comment by goern** [comment]
Ja, all new Thoth services use it and 90% of the old services have been migrated.

Frido & Harshad is the doc, if the readme is not enough

**Comment by goern** [comment]
is this stil valid?
