### ISSUE TITLE
use release of sompy

### ISSUE THREAD

**Issue by goern** [AICoE/log-anomaly-detector#146]
why is sompy required from vcs rather than a release module?

**Comment by zmhassan** [comment]
@goern Did you mean why are we using git/vcs  in our Pipfile?

There is no release module.

They don't have any wheels in pypi or even attached
https://github.com/sevamoo/SOMPY/releases

**Comment by goern** [comment]
what about https://pypi.org/project/sompy/0.1.1/ ?

**Comment by zmhassan** [comment]
We can try that but it may not be the same repo or code even.

**Comment by zmhassan** [comment]
This sompy/0.1.1 isn't the same code used for this LAD. Closing issue.
