### ISSUE TITLE
Refactor: Remove duplicate training of som/w2v from inference function

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#150]
**Is your feature request related to a problem? Please describe.**
@MichaelClifford @durandom We discussed that there is room for improvement in the code base and we do have training of the w2v and som happening twice. We also pull down data twice during a training run. I'd like to remove this duplicate effort and make some better design chooses.

In training function:
https://github.com/AICoE/log-anomaly-detector/blob/2d9ddfa7d11a79b0e350087889b756c5bcf055ce/anomaly_detector/anomaly_detector.py#L88-L114

In the inference function (To be removed):
https://github.com/AICoE/log-anomaly-detector/blob/2d9ddfa7d11a79b0e350087889b756c5bcf055ce/anomaly_detector/anomaly_detector.py#L142-L177

**Describe the solution you'd like**
I plan on removing the code in the inference function and have it do 1 thing only which is inference.

**Describe alternatives you've considered**

**Additional context**

**Comment by MichaelClifford** [comment]
Hi @zmhassan, can you clarify where the duplicate training is occuring in the inference? On line 167 I see that we update the word2vec model `self.w2v_model.update(data)`. I believe this is to account for the fact that new logs may enter the inference process that have not been seen by the original W2V training and we need some way to encode them so they can be processed by the rest of the pipeline. But if you think this is problematic, we can come up with an alternative approach. 

Beyond that, is there additional retraining happening here, specifically of the SOM model, that I'm not seeing? If so, please let me know. Thanks!

**Comment by durandom** [comment]
@zmhassan let's start by extracting all model specific code out of https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/anomaly_detector.py and into the specific model files. This way we see if there are any method calls missing in the base model interface.

Small PRs. E.g. remove the referneces to `w2v_model`. This seems to be specific to the SOMPYModel and other models might need some other preprocessing.

**Comment by zmhassan** [comment]
This was a discussion and resulted in refactoring of code. I'll close issue as its resolved.
