### ISSUE TITLE
Fix SQL Query for returning correct false positive results.

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#156]
**Describe the bug**
FactStore for feedback/api returning logs that are both true and false? Should only return logs marked as false.

https://github.com/AICoE/log-anomaly-detector/blob/2d9ddfa7d11a79b0e350087889b756c5bcf055ce/anomaly_detector/fact_store/fact_store_api.py#L63-L71

 
**Expected behavior**
Should only return records marked as  `anomaly_status ==False`
 

**Additional context**
N/A

**Comment by zmhassan** [comment]
@HumairAK Since your working on refactoring factstore please have a look at this issue.

**Comment by goern** [comment]
is this still valid?
