### ISSUE TITLE
Remove unused code in local storage class.

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#160]
**Describe the bug**

The following lines are not used in the code base and is reading from standard input. We should delete this code as its not being used.

https://github.com/AICoE/log-anomaly-detector/blob/2d9ddfa7d11a79b0e350087889b756c5bcf055ce/anomaly_detector/storage/local_storage.py#L28-L41

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zmhassan** [comment]
This is a relevant issue we can work on.

**Comment by goern** [comment]
is this still valid?
