### ISSUE TITLE
Update Threshold Calulation

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/log-anomaly-detector#18]
Update the anomaly threshold value calculation to prevent anomalies in the training data from passing undetected during the inference step.

**Comment by vpavlin** [comment]
To add context:

We are using maximum distance from Self-Organizing Map as a base for detecting anomalies (here https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/anomaly_detector.py#L179), this might lead into a state where previous anomalies (when included into training data) are no longer recognized as anomalies.

**Comment by vpavlin** [comment]
IMO this is done
