### ISSUE TITLE
When packaging up application you should use __all__ to restrict what users can import

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#181]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by durandom** [comment]
@zmhassan please remove the generic blurb and add some real content.

**Comment by zmhassan** [comment]
Sorry. Just to clarify if we use '__all__' we will be able to import easier.

**Comment by zmhassan** [comment]
This is merged.
