### ISSUE TITLE
Return the smallest instead of the last distance in the SOMPYModel

### ISSUE THREAD

**Issue by mariushegele** [AICoE/log-anomaly-detector#182]
Compare `model/sompy_model.py:40` with `model/som_model.py:88`: The smallest distance `dist_smallest` is determined in both cases, but only `som_model` returns it correctly. The `SOMPYModel` instead returns the distance in the `[n][m]` coordinate.

**Comment by zmhassan** [comment]
This PR has been merged. Thank you Marius!
