### ISSUE TITLE
Anomaly scores should be bound for better interpretability

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/log-anomaly-detector#186]
The current anomaly scores are unbounded, making the raw score itself difficult to interpret without access to other statistics about the overall distribution of anomaly scores. We should normalize the score in some way to make the anomaly scores more intuitive and interpretable by the end user. 

I suggest that we use the meta-data we collect about the anomaly scores of the training set, and generate anomaly scores with reference to the largest score found in the training set. In this way, the training anomalies will always be bound by the value of 1. Although the inference values may exceed 1, this heuristic will let the user know that any value greater than 1 is more anomalous than anything seen during training.

**Comment by zmhassan** [comment]
This patch has been merged. I'm closing this issue
