### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by oxillix** [AICoE/log-anomaly-detector#189]
Thank you for this amazing project!

**Is your feature request related to a problem? Please describe.**
When trying to implement the project, lots of time gets wasted by trying to figure out how it works properly with your ES.

**Describe the solution you'd like**
More details about the implementation process: 
- How to make ElasticSearch & ElastAlert work with this project
- How to setup fact store & its db

**Describe alternatives you've considered**
A guided installation script that does the necessary tests

**Additional context**

**Comment by zmhassan** [comment]
@oxillix for elasticsearch and elastAlert I think a good reference for documentation is available here:

[ElastAlert Docs](https://elastalert.readthedocs.io/en/latest/running_elastalert.html)

As for the fact_store and db you can use the following template to setup factstore

Instructions on how to set it up:

[Readme docs about fact_store](https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/fact_store/README.md)

**Comment by goern** [comment]
could this be closed?
