### ISSUE TITLE
Prepare testing corpus

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#2]
We need to be able to test models and their configuration reproducibly, thus we need a test data which we can use for comparison.

It needs to contain various anomalies 
* extremely anomalous text (different language, random strings?)
* medium anomalous text (take some lines and change them)
* slightly anomalous text (take some lines and change them slightly 

Also document how to run tests using this data

**Comment by MichaelClifford** [comment]
PR #38 adds an additional directory `validation_data ` that provides a script and README instructions for users to prepare a testing corpus with data from their own Elasticsearch instance and how to run the tool locally. 

The main script `generate_validation_data.py` randomly replaces some of the log entries with random strings and generates a corresponding labels file. 

The next step would be to include an automated validation checker that outputs the results of a training testing loop. (current prototype of this is in process in a jupyter notebook)

**Comment by zmhassan** [comment]
I think the goal is to have more unit test to test those use cases @vpavlin instead of generating so much random data. For now the goal is to have 1 example of sample data we can utilize to test that this code works.

**Comment by MichaelClifford** [comment]
@zmhassan, I agree. But I think we also want a single testing courpus and automated validation tests as a means of measuring the performance of models as we tune parameters, or implement different encoding and classification approaches.

**Comment by zmhassan** [comment]
@MichaelClifford I believe you added some test data into `validation_data/Hadoop_2k.json`. So I'm assuming we can close this issue.
