### ISSUE TITLE
Make fact-store configurable to validate prediction id

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#204]
**Is your feature request related to a problem? Please describe.**
When we persist predictions in fact-store we don't validate that the id exists in elasticsearch. 

**Describe the solution you'd like**
We may use other backends so make it configurable so someone can plugin their own strategy. 

**Describe alternatives you've considered**
Not check but that isn't good because this can cause many errors.

**Additional context**
N/A

**Comment by zmhassan** [comment]
We should allow folks to set VALIDATE_PREDICTION_ID=True and if so we will run the strategy for checking this. Make this configurable as folks may want to plugin different systems.
