### ISSUE TITLE
Expose and document model parameters

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#21]
There are some training and inference parameters exposed, but make sure we have a proper documentation for the parameter tuning and a plan for matrix testing with different parameters

**Comment by zmhassan** [comment]
@vpavlin Is this issue still being worked on or should we close this as its dated back 5 months back

**Comment by zmhassan** [comment]
@vpavlin I'm closing this issue. As its dated back 5 months back. I'm doing some grooming on all git issues on this repo.

**Comment by vpavlin** [comment]
That no one found time to work on it does not mean the documentation is no longer issue:)

**Comment by zmhassan** [comment]
I plan on having docs after we get the first minimal viable prototype out.

**Comment by zmhassan** [comment]
For now I'll leave this closed unless someone is ready to work on it.
