### ISSUE TITLE
Create a sink to store anomalies in DGraph for mapping relationships between systems and the anomalies it generates.

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#213]
**Is your feature request related to a problem? Please describe.**
Create a sink to store anomalies in DGraph for mapping relationships between data and predictions. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zmhassan** [comment]
Connected Feature extraction to see how things are connected.
