### ISSUE TITLE
key error when no new logs 

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/log-anomaly-detector#251]
Key Error when no new logs in the past 900 seconds.

Solution:
[Here](https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/storage/es_storage.py#L94), 
`es_data` looks like:
{'took': 4, 'timed_out': False, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}, 'hits': {'total': {'value': 0, 'relation': 'eq'}, 'max_score': None, 'hits': []}}
`es_data["hits"]["total"]` should be `es_data["hits"]["total"]["value"]`

**Comment by 4n4nd** [comment]
You might also want to add a sleep [here](https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/adapters/som_storage_adapter.py#L25-L34%5C) and try again instead of returning None

**Comment by zmhassan** [comment]
I think this issue is already fixed.
