### ISSUE TITLE
Extend ES storage backend

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#28]
- [ ] Add support for authentication with cert and key
- [x] Generalize the query

**Comment by vpavlin** [comment]
Partially solved by #31 

We still need to figure out how to properly deploy the cert and key to the cluster and bind it to the app..probably APB

**Comment by zmhassan** [comment]
This seems to be an issue 6 months back. I think its already resolved as you mount the certs into the running pod.
