### ISSUE TITLE
Reproduce

### ISSUE THREAD

**Issue by zakariafik** [AICoE/log-anomaly-detector#280]
Hello,

I cloned the repo and trying to play with it with my own data.
To do so, I followed the steps mentioned [here](https://log-anomaly-detector.readthedocs.io/en/latest/development_guide.html). The tests run without any problem. After that, I no longer know what part should I do. Could you please clarify it? 

Thanks a lot.

**Comment by zmhassan** [comment]
@zakariafik What are you interested in. For something more quick you can contribute a storage sink. We are interested in read data from many systems and writing predictions to popular cloud storage or caching technologies.

Lets start with storing perdictions to Redis:

https://github.com/AICoE/log-anomaly-detector/issues/281

**Comment by zakariafik** [comment]
@zmhassan Thank you so much for the prompt reply and for the extra explanation. 

What I am struggling with is feeding my data to the model. Where should my input data reside (suppose a .log file).

Thanks.

**Comment by zmhassan** [comment]
Hi @zakariafik you will need to set the configuration file:
Note: `LS_INPUT_PATH` is where the system will read logs from.
Note: `LS_OUTPUT_PATH` is where the system will write predictions to.

```
STORAGE_DATASOURCE: "local.source"
STORAGE_DATASINK: "local.sink"
LS_INPUT_PATH: "validation_data/orders-500.log"
LS_OUTPUT_PATH: "validation_data/aug-3_25-results.txt"
INFER_ANOMALY_THRESHOLD: 1.3
INFER_TIME_SPAN: 1
INFER_LOOPS: 1
PARALLELISM: 6
```

**Comment by zakariafik** [comment]
Many thanks for pointing that out!

While my model is training, how can I monitor it using grafana and prometheus?

**Comment by zmhassan** [comment]
The setup is a bit complex. We are working on having a make file that will set all of it up. Should be out in a week or so.

**Comment by zmhassan** [comment]
@zakariafik We have published docs on how to install grafana and prometheus for monitoring the anomaly detection. https://log-anomaly-detector.readthedocs.io/en/latest/installation.html

**Comment by zmhassan** [comment]
Let us know if you have any questions.

**Comment by zakariafik** [comment]
@zmhassan Many thanks for keeping me updated. I will give it a try and let you know if I require any further information.
