### ISSUE TITLE
Write predictions to Redis Cache

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#281]
**Is your feature request related to a problem? Please describe.**
When we get predictions we want to write it to storage sink. To contribute a custom storage sink.

**Step 1:**
I would like you to extend this class
https://github.com/AICoE/log-anomaly-detector/blob/1e25ca878981ece74866be4b8df870d041a61842/anomaly_detector/storage/storage_sink.py#L5-L15

**Step 2:**
create another function in this class.
https://github.com/AICoE/log-anomaly-detector/blob/1e25ca878981ece74866be4b8df870d041a61842/anomaly_detector/storage/storage_catalog.py#L50-L54

**Step 3:**
Add it to the catalog
https://github.com/AICoE/log-anomaly-detector/blob/1e25ca878981ece74866be4b8df870d041a61842/anomaly_detector/storage/storage_catalog.py#L60

**Additional context**

Here is an example: https://github.com/AICoE/log-anomaly-detector/blob/1e25ca878981ece74866be4b8df870d041a61842/anomaly_detector/storage/kafka_storage.py#L1-L34

Any custom configurations go in this file:
https://github.com/AICoE/log-anomaly-detector/blob/1e25ca878981ece74866be4b8df870d041a61842/anomaly_detector/config.py#L123-L127

**Comment by zmhassan** [comment]
Once your done try to test your storage adapter.
