### ISSUE TITLE
[Docs] Update docs to reflect changes made in Configuration

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/log-anomaly-detector#282]
We need to update the docs so that we can keep track of which feature flags are supported by the app. 
Example feature flags are: 
```STORAGE_DATASOURCE: "local.source"
STORAGE_DATASINK: "local.sink"```

**Comment by zmhassan** [comment]
@4n4nd Yes I'm going to make that update.

**Comment by zmhassan** [comment]
Documentation is up to date.
