### ISSUE TITLE
Grafana as part of minishift deployment

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#284]
**Is your feature request related to a problem? Please describe.**
We should have grafana preloaded as part of minishift installation

**Describe the solution you'd like**
We would need a kubernetes/openshift template that installs grafana along with preloaded dashboard.
 Also include prometheus as well

**Describe alternatives you've considered**

**Additional context**

**Comment by zmhassan** [comment]
@4n4nd I need your help on this one
