### ISSUE TITLE
Create python script to export table data from MySQL into s3 storage. For backing up feedback/false positives provided by customer.

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#303]
**Is your feature request related to a problem? Please describe.**
Often feedback is stored in MySQL database. Which we should back up regularly so we can later extract labels out of the logs processed.

**Describe the solution you'd like**
Create python script to export table data from MySQL into s3 storage. For backing up feedback/false positives provided by customer.

**Describe alternatives you've considered**

**Additional context**

**Comment by zmhassan** [comment]
If we don't do a back up then at least make MYSQL replicated and attach persistent volume on each node in case of failure or outage.
