### ISSUE TITLE
Design your elasticsearch ingest to do custom processing depending on if we are using 5.3 or 7.0 of elastic.

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#311]
For es version 5: https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-request-body.html
For es version 7: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-track-total-hits.html

_Originally posted by @4n4nd in https://github.com/AICoE/log-anomaly-detector/pull/287#issuecomment-543804089_

**Comment by HumairAK** [comment]
We should add a new environment variable ES_VERSION to dictate differences between es version <=6 logic and greater.

**Comment by zmhassan** [comment]
@HumairAK Please add that in our config and lets handle this custom behaviour in es_storage

**Comment by zmhassan** [comment]
@HumairAK I think your fix was merged so lets close this.
