### ISSUE TITLE
Add a build trigger for the staging env to the zuul config

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/log-anomaly-detector#335]
@goern @harshad16 we were trying to set up a pipeline where on every PR merge the zuul bot triggers a new build in our staging env.
[Example config](https://github.com/thoth-station/user-api/blob/8e6de922b90b3dc32d5e0be3c3a60b98e9984e98/.zuul.yaml#L9-L15), is this the correct way to do it?

Also, is there anything more that we have to do? For example, give the bot permissions in the stage namespace?

**Comment by 4n4nd** [comment]
the staging namespace is: `aiops-dev-insights-ds`

**Comment by goern** [comment]
The example config is the correct way, just add it the each pipeline that should trigger a build. The build config needs to have a generic build trigger with a certain secret, @harshad16 can create it for you in the target namespace (it's part of thoth-ops ansible playbook)
