### ISSUE TITLE
Add Coveralls badge to repo to show test coverage.

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#353]
**Describe the bug**
It's good to add some code coverage badges to repo so we can see at a glance how much percentage of coverage we currently have.

**Comment by goern** [comment]
how do you submit test coverage to coveralls?

**Comment by zmhassan** [comment]
There is integration in github and travis already.

**Comment by zmhassan** [comment]
We can add some integration inside of .travis.yaml i think.
