### ISSUE TITLE
Add pytest markers to separate which tests are for which component so we don't have to run the full test suite

### ISSUE THREAD

**Issue by zak-hassan** [AICoE/log-anomaly-detector#356]
**Is your feature request related to a problem? Please describe.**

Often we are tasked with running the whole test suite when verifying a change. 

**Describe the solution you'd like**
We don't need to do that we can mark each tests that touch each component and only run those. For example lets add these markers 

@pytest.mark.lad_core_encoder
@pytest.mark.lad_core_storage
@pytest.mark.lad_core_classifier

**Describe alternatives you've considered**

**Additional context**

**Comment by zmhassan** [comment]
then with pytest run
`pytest -m lad_core_encoder`

**Comment by zmhassan** [comment]
We should have some smoke test just to give health of system.
