### ISSUE TITLE
Enable configuration by a file (in addition to env vars)

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#37]
- [x] Use `yaml` for format

- [ ] Provide JSONSchema

- [ ] Add validation

- [ ] Figure out how to use OpenShift Template parameters

**Comment by zmhassan** [comment]
@vpavlin This is a really good idea.

**Comment by zmhassan** [comment]
This work is complete. We can provide yaml file or env vars.
