### ISSUE TITLE
ValueError: Unsupported storage provider used local.source.source

### ISSUE THREAD

**Issue by tcxdgit** [AICoE/log-anomaly-detector#371]
**Describe the bug**
After installed the log-anomaly-detector，I run the **Example Usage** as show in documents
`log-anomaly-detector run --config-yaml config_files/.env_cmn_log_fmt_config.yaml --single-run True`
but it's failed

**Screenshots**
![image](https://user-images.githubusercontent.com/23009178/70202403-89835a00-1754-11ea-9db6-a7cbbbc16113.png)

**Additional context**

**Comment by tcxdgit** [comment]
I have fixed it , config file may have error

**Screenshots**
![image](https://user-images.githubusercontent.com/23009178/70202824-d3207480-1755-11ea-956a-e7149a16eb90.png)

**Comment by zak-hassan** [comment]
@tcxdgit You can send this file up as a PR as this is good catch. :)
