### ISSUE TITLE
ui command error: OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by tcxdgit** [AICoE/log-anomaly-detector#372]
**Describe the bug**
When I run the ui command `log-anomaly-detector ui --port 8080 --debug True` in [document](https://log-anomaly-detector.readthedocs.io/en/latest/cli.html), it reports a bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/23009178/70292186-6d48f100-1818-11ea-970b-b702731839d2.png)

![image](https://user-images.githubusercontent.com/23009178/70292351-fd873600-1818-11ea-8846-10358a0f2956.png)

But my port is not in use:
![image](https://user-images.githubusercontent.com/23009178/70292377-155eba00-1819-11ea-9a45-a57c2d6a97b0.png)

**Comment by zak-hassan** [comment]
@tcxdgit  We have prometheus endpoint that runs by default on port 8080 unless you override that port.

See here:
https://github.com/AICoE/log-anomaly-detector/blob/aa2f6f9d5bc8e59ce4f1eb6f86b13e6c3537910d/app.py#L15

To make this work try:
```
log-anomaly-detector ui --metric-port 8081 --port 8080 --debug True

```

**Comment by zak-hassan** [comment]
@tcxdgit Did that solve the issue ?

**Comment by tcxdgit** [comment]
> @tcxdgit We have prometheus endpoint that runs by default on port 8080 unless you override that port.
> 
> See here:
> https://github.com/AICoE/log-anomaly-detector/blob/aa2f6f9d5bc8e59ce4f1eb6f86b13e6c3537910d/app.py#L15
> 
> To make this work try:
> 
> ```
> log-anomaly-detector ui --metric-port 8081 --port 8080 --debug True
> ```

> @tcxdgit Did that solve the issue ?

NO, it reports this:
![image](https://user-images.githubusercontent.com/23009178/70294116-75575f80-181d-11ea-96ab-0e6557f4d94e.png)

Detail of my log-anomaly-detector:
![image](https://user-images.githubusercontent.com/23009178/70294219-bb142800-181d-11ea-9272-edfab9b8540c.png)

The version of my log-anomaly-detector is 0.0.1b1

**Comment by zak-hassan** [comment]
Sorry. Typo in the command:

``` 
log-anomaly-detector --metric-port 8081 ui --port 9999
```

See our docs for details:
https://log-anomaly-detector.readthedocs.io/en/latest/cli.html

**Comment by tcxdgit** [comment]
> Sorry. Typo in the command:
> 
> ```
> log-anomaly-detector --metric-port 8081 ui --port 9999
> ```
> 
> See our docs for details:
> https://log-anomaly-detector.readthedocs.io/en/latest/cli.html

Thank you very much.
However, when I open the web page, it occurs exception
![image](https://user-images.githubusercontent.com/23009178/70402295-d5444500-1a6d-11ea-9af7-09d7d07af215.png)

![image](https://user-images.githubusercontent.com/23009178/70402083-19831580-1a6d-11ea-885d-db2a84c01492.png)
![image](https://user-images.githubusercontent.com/23009178/70402104-299af500-1a6d-11ea-93c3-be7910315c46.png)

**Comment by zak-hassan** [comment]
@tcxdgit . The fix is now cut and released. Try to install:

```

pip install log-anomaly-detector==0.0.2

```

**Comment by zak-hassan** [comment]
![image](https://user-images.githubusercontent.com/1269759/70403908-46501200-1a06-11ea-8681-31081de00a8b.png)

**Comment by zak-hassan** [comment]
@tcxdgit let me know if you can use this.

Note you should have this env var set as this system might be used by many apps. Customer ID will be a field tracked in the database.
```
export CUSTOMER_ID="#1234567"
```
Also by default we use sqlite for the database but if you want to connect to any database supported by sqlalchemy try:
```
export SQL_CONNECT="mysql+pymysql://username:password@localhost/factstore"
```

**Comment by tcxdgit** [comment]
> @tcxdgit let me know if you can use this.
> 
> Note you should have this env var set as this system might be used by many apps. Customer ID will be a field tracked in the database.
> 
> ```
> export CUSTOMER_ID="#1234567"
> ```
> 
> Also by default we use sqlite for the database but if you want to connect to any database supported by sqlalchemy try:
> 
> ```
> export SQL_CONNECT="mysql+pymysql://username:password@localhost/factstore"
> ```

I can use it now. Thank you!

**Comment by zak-hassan** [comment]
I'm assuming that this issue is now resolved. So please reopen if you would like to discuss further @tcxdgit
