### ISSUE TITLE
More documentation and examples for onboarding

### ISSUE THREAD

**Issue by fflakito** [AICoE/log-anomaly-detector#379]
Hi, I don't know if the project is dead, I'm wondering because I see there hasn't been a single commit for half a year.

If it isn't: as a relative newbie in software engineering, distributed applications and ML, I must say I would need (much) more context and examples to be able to use this project, which otherwise seems to really fit my business needs.

I hope I'm not too far off point here. Exciting project anyway ! :)

**Comment by iarungv** [comment]
Hi, Following up on this request, do we have any usage samples for this module. I would like to start with just giving a text log file as input and go one step at a time. Any help would be appreciated. Thanks!
