### ISSUE TITLE
Event correlation request

### ISSUE THREAD

**Issue by nadzyah** [AICoE/log-anomaly-detector#386]
**Is your feature request related to a problem? Please describe.**
Using LAD in the production, we also meet amounts of anomaly logs. Even if there're only 0.1% of anomalies and we have 1000000 logs, there're 1000 anomaly events. Of course, 1000 is much less than 1000000, but it's still hard to take action on all these logs.

**Describe the solution you'd like**
Are you looking to apply any event deduplication and then correlation for anomaly logs? For example, it may be possible to find the relations between detected anomaly events (for instance, using time-based, attribute-based or other clustering methods).

This tool can become much more useful if it provides any event correlation mechanism. As the result, we can have 10 incidents based on detected 1000 anomalies.

**Comment by durandom** [comment]
@nadzyah this project has become a bit stale. But we're still interested in analyzing log streams.
@MichaelClifford  can point you to some more recent implementations. 

@dhonza from the Prague University also implemented some solutions in https://github.com/LogAnalysisTeam/ml4logs
You can check out a recent presentation at 
https://www.youtube.com/watch?v=n6_ywF-Zt6U&list=PLKNUArbT35cBMrl6T9Bpke339irzs5ARW&index=11

**Comment by MichaelClifford** [comment]
Hello @nadzyah these are great suggestions for improving the LAD tool. However, as mentioned above,  this project is currently not being maintained, so it may be some time before such a solution is implemented. 

You can take a look  at some more recent work [here](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/gcsweb-ci/build-logs/build_log_term_freq.ipynb) on log analysis that we've done as part of an [AI4CI](https://github.com/aicoe-aiops/ocp-ci-analysis) project. 

Hope that helps :slightly_smiling_face:
