### ISSUE TITLE
Create S3 storage backend

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#4]
As this service needs to be integrated into DataHub, which depends heavily on object storage (Ceph flavour of S3 Object Storage), create a storage backend for use case where data are stored in S3

**Comment by zmhassan** [comment]
We are defaulting to using persistent volumes to mount into ceph. For now the plan is not to implement this as its not in our requirements for MVP-1

**Comment by vpavlin** [comment]
Where are the requirements for MVP-1 specified?

**Comment by zmhassan** [comment]
https://github.com/AICoE/log-anomaly-detector/milestones

**Comment by zmhassan** [comment]
I can write up a more detailed document. And we can take it internally and comment. But from what I was told. We want to have a simple prototype to demo next week.
