### ISSUE TITLE
Performance of Training is bottlenecked because of limits set on max number of  lines to process

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#43]
## Problem
When processing log data by default there is a limits set to how many rows of data the program can process. Is it possible for to have higher values as defaults and when we are training with public dataset can we process more lines as we are not facing the limitations places on us due to elasticsearch limits.

## Changes
https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/config.py#L55-L66

```   
# Number of seconds specifying how far to the past to go to load log entries for training TODO: move to es storage backend
    TRAIN_TIME_SPAN = 900
    # Maximum number of entries for training loaded from backend storage
    TRAIN_MAX_ENTRIES = 10000
    # Number of SOM training iterations TODO: move to model config
    TRAIN_ITERATIONS = 4500
```

**Comment by zmhassan** [comment]
To process 790000 lines of logs it took: 

```bash
Whole Process takes 44.46676826477051 minutes
```

**Comment by zmhassan** [comment]
When we train with 2000 lines of logs it takes:

```bash
Whole Process takes 0.9336263338724772 minutes
```

**Comment by vpavlin** [comment]
I am not sure what is the goal here. You can configure the number of entries via env var

**Comment by MichaelClifford** [comment]
@zmhassan  

> When processing log data by default there is a limits set to how many rows of data the program can process. Is it possible for to have higher values as defaults and when we are training with public dataset can we process more lines as we are not facing the limitations places on us due to elasticsearch limits.

Yes, that's fine. In fact, we should probably set the defaults to coincide with the validation data set (parameters TBD). But as @vpavlin mentioned, I'm not sure why this is a bottleneck as the number of entries allowed is fully configurable.  

That said, you are right that it is not really needed for local testing. The reason we provide the option for limiting the number of entries is really only a concern for pulling data from ES.

**Comment by vpavlin** [comment]
Yeah, limiting to the test data set makes sense

Also, for what it's worth, I have created this issue https://github.com/AICoE/log-anomaly-detector/issues/53 regarding current limits our ES backend

**Comment by zmhassan** [comment]
The motivation for this issue is for to have more performant code. As the size of the data grows the program slows down as we see with 790000 lines of logs it slows down to 44 mins to complete end to end? With elasticsearch it may take longer as we are limited with how much data we can pull down at a given time.

**Comment by vpavlin** [comment]
Ok, I understand your last comment, but it does not sound very connected to the title of the issue and the description. The limits do not influence performance - just the amount of data used for training/inference, so changing limits will not influence performance at all (obviously less data -> less time needed for training, but that does not mean better performance).

If you think there is something we can do to speed up training or inference, feel free to provide suggestions - I am sure the @MichaelClifford's implementation of the core algorithm can be tuned:)

**Comment by MichaelClifford** [comment]
Yes, there are certainly performance inefficiencies that can be addressed, #44 for example. But as far as 44 minutes for training almost 800k logs, I'm not sure that is a real blocker. I'll need to look at log frequency values a bit more closely, but I'm fairly confident that 800k logs represents far more than an hour of data. So if it takes less than an hour to train it, then it should be fine. I would expect training times to be significantly longer than inference times. That's the main reason we train much less often and why we want to decouple training and inference.

**Comment by vpavlin** [comment]
For reference the one service that we monitor in our internal infra produces ~30k logs per day (24h) (last I checked..)

**Comment by zmhassan** [comment]
Even the 30k logs we should get the most performance out of.

**Comment by zmhassan** [comment]
Seems that we have come to a concensus on this issue. I'll close this issue.
