### ISSUE TITLE
Performance of get_anomaly_score function parallelism

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#44]
for a log file with 700,000 rows 'get_anomaly_score' gets called 700,000 times. Is it possible to do some of this in parallel either via thread or parallel process ? 

```python
    def get_anomaly_score(self, log):
        """Compute a distance of a log entry to elements of SOM."""
        # convert log into vector using same word2vec model (here just going to grab from existing)
        dist_smallest = np.inf
        for x in range(self.model.shape[0]):
            for y in range(self.model.shape[1]):
                dist = np.linalg.norm(self.model[x][y]-log)  # cosine(som[x][y],log)#np.linalg.norm(som[x][y]-log)
                if dist < dist_smallest:
                    dist_smallest = dist

        return dist_smallest
```

**Comment by MichaelClifford** [comment]
@zmhassan Good Idea. There is no reason that I can see that would stop this from running in parallel. I'll look at some parallel processing methods for this loop.

**Comment by vpavlin** [comment]
whoever is going to implement this, try to think about how to tie it to resource limits in OpenShift (i.e. we probably don't want 10 busy thready if the CPU limit is 0.1 CPU, same it does not make sense to have 10 CPUs allocated if we only are able to use one:) ).

**Comment by zmhassan** [comment]
This seems to be fixed since @MichaelClifford added the SOM library with Parallesm
