### ISSUE TITLE
Is it possible to make the `save_visualisation` save optional?

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#45]
Wonder where your using the visualization U-map.png ? Is it possible to make that optional to save that image.

```python
def save_visualisation(self, dest):
    ...
```

And maybe removing all the matplotlib stuff we are not using any visualizations in this app
```python
matplotlib.use("agg")
from matplotlib import pyplot as plt
```

**Comment by zmhassan** [comment]
Wonder if we can strip out as much stuff as we can to this program run faster.

**Comment by MichaelClifford** [comment]
@zmhassan   `save_visualzition` can definitely  be made optional. Its nice to have during validation, but does not need to be run on each training step.

**Comment by zmhassan** [comment]
@MichaelClifford Maybe we can use MLFlow to track this visualization and model for us. For now I'll close this we can keep it. Its up to you.
