### ISSUE TITLE
Locking down versions for pipfile pipenv is failing to instal latest versions

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#48]
I'm getting an error unable to download 

CI link:
https://travis-ci.org/AICoE/log-anomaly-detector/builds/458659855?utm_source=github_status&utm_medium=notification

```python
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
pylint = "*"
"flake8" = "*"
pydocstyle = "*"
"pep8" = "*"
pytest = "*"

[packages]
"elasticsearch5" = "*"
gensim = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
scipy = "*"
tqdm = "*"
prometheus_client = "*"


[requires]
python_version = "3.6"

```

**Comment by zmhassan** [comment]
Instead of using `*` can we use locked down versions?

**Comment by durandom** [comment]
sure. I'd lock down on major versions

**Comment by vpavlin** [comment]
@fridex What is the right way to do this so that we can use Thoth? For some reason the Pipfile.lock still throws an exception: https://github.com/AICoE/log-anomaly-detector/pull/40

**Comment by fridex** [comment]
> Instead of using * can we use locked down versions?

BTW for this purpose is the Pipfile.lock file.

> @fridex What is the right way to do this so that we can use Thoth? For some reason the Pipfile.lock still throws an exception: #40

This at first shot looks like a pipenv issue. Maybe try a different version?

Also, I would suggest to use ``pipenv install --deploy`` in the travis.yaml.
