### ISSUE TITLE
Create documentation for developers

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#5]
Developers need to know how to
* create new Storage Backend
* new models

**Comment by zmhassan** [comment]
@vpavlin Good idea. Seems like this git issue is 5 months back. I was thinking to close this issue if no one is working on this.

**Comment by zmhassan** [comment]
This is actually a duplicate issue on creating docs. I'll reopen this when someone is working on documentation. Lets schedule this for after the first prototype gets rolled out and we have users

**Comment by zmhassan** [comment]
We will be updating the docs with details for folks to get started with the project.

**Comment by zmhassan** [comment]
We will be updating the docs with details for folks to get started with the project.

**Comment by zmhassan** [comment]
We have docs. Closing this issue as work is code complete.
