### ISSUE TITLE
s3 store for models produced after training

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#50]
When training the model it would be good to have the ability to store the models in s3. Later we can tie this in with the inference to serve the models. We may have to design around how to roll out new versions of the model but in simple case. See visual below:

![model-s3](https://user-images.githubusercontent.com/1269759/48958483-48475000-ef2d-11e8-9325-6c152f654ed0.jpeg)

**Comment by zmhassan** [comment]
Everything required for training can be a separate pod and everything required for inference could be a separate pod.

**Comment by vpavlin** [comment]
Yeah, that makes sense. From the implementation point of view, I would suggest to extend 

https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/model/base_model.py#L30

and store to S3 automatically if configuration (S3 endpoint, secret key, key id and bucket/path) is provided

**Comment by zmhassan** [comment]
Thanks. Yes good idea.

**Comment by zmhassan** [comment]
We have already included code to store into s3 in the mean time currently we have ceph s3 pvc's already setup.

**Comment by zmhassan** [comment]
This is done we can close this.
