### ISSUE TITLE
[Bug] in anomaly detector load_data function for local mode

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#52]
When in local mode we should skip this function completely and just check if file is empty instead of trying to check elasticsearch if it contains data.

Line 68 in anomaly_detector.py
```python
        data, raw = self.storage.retrieve(time_span, max_entries)
```

imho lets check for local mode or elasticsearch mode before doing doing all this logic.

**Comment by vpavlin** [comment]
It does not check ElasticSearch, storage has a base class which requires 2 methods to be implemented  `retrieve` and `store_results`. See https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/storage/local_storage.py#L26 for implementation of local storage
