### ISSUE TITLE
ES backend should be able to pull more log messages than ES can provide on a single call

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#53]
Right now we are limited by limit of messages ES will return for a single API call (in our ES deployment that is 10k). We should (for the sake of consistency and daily seasonality) train on 24 hours of data - which will probably be more than the 10k messages.

We should implement this

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

to allow pulling more messages for training

**Comment by zmhassan** [comment]
Not trying to introduce too much changes to architecture but I have another alternative:

@vpavlin What if we skip ES completely and have the log messages stream to kafka then have a spark steaming job that will append the new messages to parquet storage which can be split. We could organize it into buckets and have it partitioned per day (24 hours).

**Comment by vpavlin** [comment]
Yeah, that is a valid point, we should decide whether to go directly with Kafka or base it on S3..we have issues for both:)

https://github.com/AICoE/log-anomaly-detector/issues/3
https://github.com/AICoE/log-anomaly-detector/issues/4

We surely will need S3 integration for you model storage proposal and for https://github.com/AICoE/log-anomaly-detector/issues/35

All the data from Kafka should already go to S3 in our deployment (IIUC), so what you are saying is probably half way there from the infra point of view.

**Comment by goern** [comment]
is this still valid?
