### ISSUE TITLE
Allow users to give feedback on wrong model prediction

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#60]
When we push out elasticsearch alerts we can include a url to the webapplication for user feedback.

https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/anomaly_detector.py#L185-L206

**Comment by zmhassan** [comment]
@MichaelClifford What do you think can we add a extra field in here: 

https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/anomaly_detector.py#L185-L206

`To include s.['feedback_url']="feedback:9090/anomaly-feedback/187272727263"`

**Comment by MichaelClifford** [comment]
@zmhassan yes, including a feedback field there should be fine.
