### ISSUE TITLE
Create sample .env file for developers to quickly run this app

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#69]
To make it easy for someone to clone this repo and run the training. We should include a .env file that works and performs training.

**Comment by durandom** [comment]
It's pretty common to have an `.env.example` and require people to copy it to `.env`

Look [here](https://github.com/bkeepers/dotenv#should-i-commit-my-env-file)
It's debatable, personally I think `.env` should be in `.gitignore`, as it will contain sensitive data at some point. And people will make adjustments to some settings and then you'll have to exclude them from your next commit or revert... etc.

If you want developers to get started quick, I think it's better to create some bootstrapping scripts or a `Makefile` or other task runners...

**Comment by zmhassan** [comment]
Good point. I should include a make file as part of the PR.

**Comment by zmhassan** [comment]
We have a --config-yaml parameter we can pass in to the training run and all configurations can be passed in via file instead of env vars. 

I'll close this for now as the code is already merged for this.

**Comment by zmhassan** [comment]
Actually we should keep this open as I should include a Makefile for developers to get up and running.

**Comment by zmhassan** [comment]
This is done.
