### ISSUE TITLE
Decouple training and inference

### ISSUE THREAD

**Issue by vpavlin** [AICoE/log-anomaly-detector#7]
The model is retrained after N inference loops. This retraining blocks inference as they both run sequentially. Decouple training and inference so that the system continuously infers and training happens in the background

**Comment by zmhassan** [comment]
@MichaelClifford and I had a meeting to discuss this. I think we want to revisit the design of this. 

## Proposed changes:
1. Have a separate pod for training.
2. Seperate pod for inference.
3. We may look into rolling out versions using istio **maybe**

**Comment by MichaelClifford** [comment]
Sounds, good. I just figured since this issues already existed this would be a good spot to track it.

**Comment by vpavlin** [comment]
> * Have a separate pod for training.
> * Seperate pod for inference.

How will these pod share the model? (they cannot do it via PV)

**Comment by zmhassan** [comment]
>> How will these pod share the model? (they cannot do it via PV)

We will utilize s3

**Comment by zmhassan** [comment]
This has been setup. Via parameter or env var you can do training separate from inference.
