### ISSUE TITLE
Track Model, Input dataset and anomalies found in s3

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#74]
We are able to disable the inference from notifying us on false anomalies however we don't have a mechanism to reproduce that anomaly as data is streaming in. I'm proposing that we track the following artificates together using mlflow:
1) Model Files: som.model, w2v.model
2) Input dataset: We can store the 10,000 rows of logs into a parquet file and upload it with our experiment
3) Anomaly dataset: We can insert into a parquet file all the anomalies that where found.
4) Metrics:
* Number of anomalies found
* Number of false anomalies produced in the model

Once our user report an anomaly our data scientists can be working in parallel to improve the training of the model to get smarter.

@durandom @MichaelClifford @vpavlin What are your thoughts on this approach?

**Comment by MichaelClifford** [comment]
@zmhassan, I thought the fact-store saved the anomalies providing us with the ability to reproduce them. Can you clarify what the problem is that this proposal is addressing? Sorry, I'm just not 100% clear on it : )

**Comment by zmhassan** [comment]
True. I'd like to understand where we can plugin the data for the false anomalies in the current implementation of training of the models? So lets break this into 2 tasks:
1) Masking false anomalies from notifying users.
2) Having the training query fact-store when training models and self-improving. 
@MichaelClifford What do you think?

**Comment by MichaelClifford** [comment]
@zmhassan  So I think we want to add some additional logic to the `_load_data` function so that we also query the fact-store and add the false anomalies to the variable `data` if it is available when training is run.   https://github.com/AICoE/log-anomaly-detector/blob/187b360663b2e28a798f937184fdbc3c5269e398/anomaly_detector/anomaly_detector.py#L70-L77 

we may also need to create another method similar to `storage.retrieve` for this.

https://github.com/AICoE/log-anomaly-detector/blob/187b360663b2e28a798f937184fdbc3c5269e398/anomaly_detector/storage/storage.py#L20-L23

**Comment by zmhassan** [comment]
👍  I like this. Good idea.

**Comment by zmhassan** [comment]
Thats sounds good for the training side.

For the inference bit I'm thinking to have us create AnomalyFact objects. When we set the property self.anomaly=True then we will trigger it to pull the fact-store to validate.

```python
class AnomalyFact:
    """
    AnomalyFact

    Core class for anomaly validation
    """

    def __init__(self, msg, score=0, anomaly=False):
        """
        Constructor for anomaly fact and listeners that will get triggered if this anomaly is marked as True

        :param msg:
        :param score:
        :param anomaly:
        """
        self._observers = []
        self._msg=msg
        self._score=score
        self._anomaly=anomaly


    @property
    def score(self):
        return self._score

    @score.setter
    def score(self, score):
        self._score = score

    @property
    def anomaly(self):
        return self._anomaly

    @anomaly.setter
    def anomaly(self, anomaly):
        self._anomaly = anomaly
        if self._anomaly == True:
            self.notify(self)

    def attach(self, observer):
        if observer not in self._observers:
            self._observers.append(observer)

    def detach(self, observer):
        try:
            self._observers.remove(observer)
        except ValueError:
            print("error")

    def notify(self, modifier=None):
        for observer in self._observers:
            if modifier != observer:
                observer.update(self)



class AnomalyFactChecker:
    def __init__(self,name):
        self.name=name


    def update(self, subject):
        print(" AnomalyFactChecker {} : {} has score {} is anomaly: {}".format(self.name,subject._msg, subject.score, subject.anomaly))
        # TODO: Check Is this really an anomaly?
        #       - HTTP Rest call to anomaly fact-store to see if this was reported as false
        #       - Once it gets a no then we proceed with next step which is


```

**Comment by zmhassan** [comment]
I'll be shuffling some of the code and would like to design this a bit better.

**Comment by zmhassan** [comment]
This is a duplicate issue. We will move all work on feedback loop for updating retraining to issue #105
