### ISSUE TITLE
Revisit the prometheus metrics and design grafana dashboard that will show metrics

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#77]
Whats involved here:
* Deploy prometheus-pushgateway
* Add push metrics to anomaly-detector to push metrics to the pushgateway.
* Create a simple grafana dashboard for showing the performance and anomaly in one pain of glass.

**Comment by durandom** [comment]
Could we start with exposing prometheus metrics from the long running LAD service?
Like a rate of found anomalies etc?

**Comment by zmhassan** [comment]
Good point. We do have some metrics exposed which @vpavlin included prior to be joining this project. I was thinking and creating a list of things we want to track in prometheus.

**Comment by zmhassan** [comment]
This is done.
