### ISSUE TITLE
Revisit notification system and consider using alertmanager 

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#78]
Consider that elasticsearch is a great document search system and our system currently supports using ElastAlert to notify users on anomaly detected. I'm not sure if it is the best design. What if we used a cloud native technology like alertmanager. 

It looks like alertmanager has a more similar system in configuring alerts. Also good for us to dog food our cloudnative stack prometheus+alertmanager which is included in OpenShift.

@durandom What do you think?

https://github.com/prometheus/alertmanager/issues/259

![image](https://user-images.githubusercontent.com/1269759/54167691-54eea600-4441-11e9-9c74-7326a2a40ca2.png)

**Comment by zmhassan** [comment]
@vpavlin @MichaelClifford What do you'll think about this idea?

**Comment by durandom** [comment]
I like the idea of integrating alertmanager and prometheus into the setup.

But prometheus is more for timeseries data, so we can't add a logline to it. We could abuse a label to carry the log_id or something, but that's a bad practice.

I see prometheus more in the area of monitoring LAD and maybe reporting on the number of found anomalies etc.

**Comment by zmhassan** [comment]
Good point @durandom 
What I was thinking was just storing the id's as labels but the data would get stored in fact-store.

**Comment by durandom** [comment]
This would be a mis-use of labels, as the value space for the label is
infinte.
Prometheus explictly discourages something like this

**Comment by zmhassan** [comment]
What if we embed the name of the metric in the metric name. For example:

```
anomaly_detected_938939383832{ labels { [ score:3.5], [prediction_id=938939383832], [system="log-anomaly-detector"] }
anomaly_detected_4847483838383{ labels { [ score:3.5], [prediction_id=4847483838383], [system="log-anomaly-detector"] }
anomaly_detected_5432948490343{ labels { [ score:3.5], [prediction_id=5432948490343], [system="log-anomaly-detector"] }
anomaly_detected_383832938939{ labels { [ score:3.5], [prediction_id=383832938939], [system="log-anomaly-detector"] }

```

**Comment by zmhassan** [comment]
Consider if you had multiple anomalies that happened in the system. For each anomaly detected it could reach infinite numbers of metrics. You are right it might not scale. I'll research some alternative paths we can look at. But let's keep this issue open to discuss.

**Comment by zmhassan** [comment]
@durandom What about using a database for storage then? Would that be another alternative to this approach. Perhaps we just push just the metrics related stuff to prometheus and the heavy data into some storage system? We can point some gui like superset to visualize the reports on anomalies?

**Comment by durandom** [comment]
yes. we could use a DB or redis or something for backing the fact store

**Comment by zmhassan** [comment]
Sweet. That would eliminate a lot of things. Awesome 👍 .

**Comment by vpavlin** [comment]
I am slightly confused now - what is that we are solving actually?

I would highly discourage over-complicating things unless necessary

My understanding:
a) You want better alert management, because ElastAlert is not user friendly enough for creating nice templates
b) For that you would like to use Alert Manager, which brings in Prometheus (not as a monitoring tool, but as a part of workflow for LAD)
c) We cannot use Prometheus to store info about anomalies, so we bring in a database and prometheus and somehow connect those?

It sounds to me that we are adding Prometheus, Alert Manager and a database just to have nicer emails - is that correct?:-)

Can we rather start using fact store with ElastAlert and think about it if it proves problematic?

Different story would be "we need a different storage backend for fact store" - but do we? I thought my  initial concerns about storing stuff in S3 were covered, so we are fine for now - or am I misunderstanding?

**Comment by zmhassan** [comment]
@vpavlin Good point.

 ### Problems 
Our dataflow today:
- We are making a call to elasticsearch (getting log data) -> training a models -> inference-> pushing to elasticsearch-> ElastAlert (trigger emails).
- I'm not opinionated in the technical choices of what technology we use but that it can scale. Today we are limited in how much data we can pull down from ElasticSearch which is about 10,000 rows of logs or it may fail.
- We have an infinite loop that times out and waits for some time and restarts the whole process. If there is no data it times out. 

### Proposal
1. Email issue

- I think we both agree that the email issue is solved via ElastAlert. We don't have to use AlertManager. And the purpose of using AlertManager was not to just send emails but also to trigger an alert based on metrics pushed to prometheus. 

2. Metrics

- Metrics can be easily monitored within LAD_Core and we get triggered can be easy handled by prometheus. 

3. Scale and Performance
- In terms of limits placed on the system I was looking to see if there was an alternative to elasticsearch as its a search tool not a database. 
- I was planning on adding an orm that would connect to a database and write our metadata there.

**Comment by durandom** [comment]
@zmhassan do you mind closing this issue and create / re-use dedicated issues for each of the topics?
This is turning into a hairball

**Comment by zmhassan** [comment]
Good idea. I'll break these up

**Comment by zmhassan** [comment]
Closing this issue as a lot of this discussions exist in other issues or have been resolved.
