### ISSUE TITLE
quay automated builds for container images via latest commit. 

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#81]
In dockerhub they have build hocks that will build your container images via a git commit. This will eliminate the extra step of running s2i. Quay.io provides similar automation for building images via git commit. 

Do we want to automate this process?

### Action Items:
- [ ]  Configure pushes from git are automatically built by quay.io

**Comment by zmhassan** [comment]
Hi @4n4nd I was wondering if you did something like this before?

**Comment by durandom** [comment]
I actually love building the image on openshift. Why dont we stick with that?

**Comment by zmhassan** [comment]
We could do that too. Just was looking for a more automated build process.

**Comment by vpavlin** [comment]
What is the problem with automating builds on OpenShift?

If you want to build in Quay or DockerHub we have to ditch the s2i and build from Dockerfile

**Comment by zmhassan** [comment]
We could still have s2i it doesn't have to go away. I was suggesting to have the commits trigger a build of the latest image. Of whatever is in `upstream/master`

**Comment by vpavlin** [comment]
How do you build s2i in Quay?

**Comment by zmhassan** [comment]
I don't know if quay supports s2i. But my thought was just to include a dockerfile that uses centos-py36 base image.

**Comment by 4n4nd** [comment]
I think keeping an archive of old images is a good idea, but triggering a build on every commit seems like an overkill. Maybe we can do releases and each release can trigger a new build.

**Comment by zmhassan** [comment]
So seems like we don't have consensus on automated build process with quay.io . I'll close this issue and assume that we don't have this requirement on automated image builds.
